### ISSUE TITLE
Recent change breaks mounting

### ISSUE THREAD

**Issue by hrehfeld** [abique/tmfs#20] opened 2020-04-01 15:35 UTC
No time for a better report atm, but the recent change to c++17 makes tmfs mount some version of my own filesystem into mountpoint instead of the timemachine backup. the exact same command with the previous commit (+cmake boost fix) works.

(and thanks a bunch for the awesome speed of the fix! :-))

**Comment by abique** [comment] 2020-04-01 20:30
Unfortunately I can't test it myself.
I don't have time machine backup, I initially implemented it for a friend.

**Comment by abique** [comment] 2020-04-01 21:00
I added some debug logs, could you try again and copy the output please?

**Comment by abique** [comment] 2020-04-07 07:07
Did you take the master branch or the r6 tag?
If you can build it from master that would be good.

**Comment by hrehfeld** [comment] 2020-04-07 09:58
`master` is what I've tried :frowning_face:

**Comment by cnagyxyz** [comment] 2020-05-02 16:42
Below is a snippet of the debug log. It seems like the problem is in the _get_real_path function. Appending the '/' to the real_path causes it to be wiped out.

```
get_real_path("/.Trash") -> /.Trash
get_real_path("/.Trash-1000") -> /.Trash-1000
get_real_path("/.xdg-volume-info") -> /.xdg-volume-info
get_real_path("/autorun.inf") -> /autorun.inf
get_real_path("/") -> /
get_real_path("/") -> /
get_real_path("/root") -> /root
get_real_path("/boot") -> /boot
get_real_path("/run") -> /run
```

If I modify the for loop that appends to first 4 parts to skip over the first part then the filesystem is mounted properly

```
  for (int i = 0; i < 4 && it != clean_path.end(); ++i, ++it) {
  	 if (i > 0) {
    	real_path /= *it;
 	 }
  }
```

Here is the debug log with that change:

```
get_real_path("/.Trash") -> /home/cnagy/Mount/MainDisk/Backups.backupdb/.Trash
get_real_path("/.Trash-1000") -> /home/cnagy/Mount/MainDisk/Backups.backupdb/.Trash-1000
get_real_path("/.xdg-volume-info") -> /home/cnagy/Mount/MainDisk/Backups.backupdb/.xdg-volume-info
get_real_path("/autorun.inf") -> /home/cnagy/Mount/MainDisk/Backups.backupdb/autorun.inf
get_real_path("/") -> /home/cnagy/Mount/MainDisk/Backups.backupdb
get_real_path("/") -> /home/cnagy/Mount/MainDisk/Backups.backupdb
get_real_path("/.") -> /home/cnagy/Mount/MainDisk/Backups.backupdb/.
get_real_path("/..") -> /home/cnagy/Mount/MainDisk/Backups.backupdb/..
get_real_path("/.RecoverySets") -> /home/cnagy/Mount/MainDisk/Backups.backupdb/.RecoverySets
get_real_path("/.spotlight_repair") -> /home/cnagy/Mount/MainDisk/Backups.backupdb/.spotlight_repair
get_real_path("/.spotlight_temp") -> /home/cnagy/Mount/MainDisk/Backups.backupdb/.spotlight_temp
get_real_path("/Christopher Nagy’s MacBook") -> /home/cnagy/Mount/MainDisk/Backups.backupdb/Christopher Nagy’s MacBook
```

**Comment by abique** [comment] 2020-05-02 17:26
Your suggestion is on the master branch.
Thank you very much!

**Comment by abique** [comment] 2020-05-02 17:29
@hrehfeld Do you have some time to try the new fix? Thank you very much.

**Comment by cnagyxyz** [comment] 2020-05-02 18:52
@abique I just tried your fix but it didn't work. By starting the counter at 1, the iterator doesn't skip over the root element of the path. I've submitted a pull request that converts the path into a relative path before appending parts to the real_path. I think that makes things more clearer.

**Comment by abique** [comment] 2020-05-02 19:35
@cnagyxyz Thank you a second time! I've merged your change!

**Comment by abique** [comment] 2020-05-04 08:08
I suppose that it works now, @hrehfeld I close the issue, if it does not work for you please re-open.

Thank you.

**Closed by abique** 2020-05-04 08:08 UTC

**Comment by hrehfeld** [comment] 2020-05-04 08:38
Thanks for the work so far! Will check once I have physical access to the timemachine disk again.

4 May 2020 10:09:01 Alexandre Bique <notifications@github.com>:
